application: tweet-2-rss
version: 1-2
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /feed/.*
  script: feed.app
  
- url: /twitter_connect
  script: twitter_connect.app
  
- url: /oauth_callback
  script: oauth_callback.app

- url: /builder
  script: builder.app

- url: /static
  static_dir: view/static
  
- url: /.*
  script: main.app
  
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
